fix: Resolve GHCR Package Name for Cleanup
Signed-off-by: Alberto Perdomo <aperdomo@redhat.com>

diff --git a/.github/workflows/build-images.yaml b/.github/workflows/build-images.yaml
--- a/.github/workflows/build-images.yaml
+++ b/.github/workflows/build-images.yaml
@@ -208,7 +208,35 @@ jobs:
             API_SCOPE="users"
           fi
 
-          PACKAGE_BASE="/${API_SCOPE}/${GITHUB_REPOSITORY_OWNER}/packages/container/benchflow/versions"
+          PACKAGE_NAME="${GITHUB_REPOSITORY#*/}/benchflow"
+          PACKAGE_NAME_ENCODED="${PACKAGE_NAME//\//%2F}"
+          PACKAGE_BASE="/${API_SCOPE}/${GITHUB_REPOSITORY_OWNER}/packages/container/${PACKAGE_NAME_ENCODED}/versions"
+
+          if ! gh api "${PACKAGE_BASE}?per_page=1" >/dev/null 2>&1; then
+            PACKAGE_NAME="$(
+              gh api "/${API_SCOPE}/${GITHUB_REPOSITORY_OWNER}/packages?package_type=container&per_page=100" \
+                --jq '
+                  map(select(
+                    (.name == "benchflow")
+                    or (.name == "'"${GITHUB_REPOSITORY#*/}"'/benchflow")
+                    or (.name | endswith("/benchflow"))
+                  ))
+                  | sort_by(.updated_at)
+                  | reverse
+                  | .[0].name // ""
+                '
+            )"
+
+            if [[ -z "${PACKAGE_NAME}" ]]; then
+              echo "Could not resolve the GHCR package name for benchflow" >&2
+              exit 1
+            fi
+
+            PACKAGE_NAME_ENCODED="${PACKAGE_NAME//\//%2F}"
+            PACKAGE_BASE="/${API_SCOPE}/${GITHUB_REPOSITORY_OWNER}/packages/container/${PACKAGE_NAME_ENCODED}/versions"
+          fi
+
+          echo "Pruning package ${PACKAGE_NAME}"
           gh api --paginate "${PACKAGE_BASE}?per_page=100" | jq -s 'add' > versions.json
 
           mapfile -t DELETE_IDS < <(
